using System;
using System.ComponentModel.DataAnnotations;

namespace KonferenscentrumVast.Models
{
    /// <summary>
    /// Represents file metadata stored in PostgreSQL database
    /// Contains GDPR-compliant information about uploaded files
    /// Actual file content is stored in Azure Blob Storage
    /// </summary>
    public class UploadFile
    {
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Secure filename generated by system (GDPR: no personal data in filenames)
        /// Format: {type}_{timestamp}_{guid}.{extension}
        /// Example: contract_20231201143045_abc123def456.pdf
        /// </summary>
        [Required]
        [StringLength(255)]
        public string SecureFileName { get; set; }

        /// <summary>
        /// Original filename from user (stored for reference but not used in storage)
        /// GDPR: Limited retention period may apply
        /// </summary>
        [StringLength(255)]
        public string OriginalFileName { get; set; }

        /// <summary>
        /// File type category: 'contract' or 'image'
        /// Determines storage location and processing rules
        /// </summary>
        [Required]
        [StringLength(50)]
        public string FileType { get; set; }

        /// <summary>
        /// File size in bytes - used for validation and reporting
        /// </summary>
        [Required]
        public long FileSize { get; set; }

        /// <summary>
        /// File extension in lowercase (.pdf, .jpg, etc.)
        /// Used for validation and content type determination
        /// </summary>
        [Required]
        [StringLength(10)]
        public string FileExtension { get; set; }

        /// <summary>
        /// Full URL to access the file in Azure Blob Storage
        /// Files are stored with private access, URLs may require SAS tokens
        /// </summary>
        [Required]
        [StringLength(500)]
        public string StorageUrl { get; set; }

        /// <summary>
        /// Azure Blob Storage container name where file is stored
        /// Separate containers for different file types if needed
        /// </summary>
        [Required]
        [StringLength(100)]
        public string ContainerName { get; set; }

        /// <summary>
        /// Optional reference to related booking
        /// GDPR: Links files to specific business transactions only when necessary
        /// </summary>
        public int? BookingId { get; set; }

        /// <summary>
        /// Optional reference to related facility
        /// Used for facility images and related documents
        /// </summary>
        public int? FacilityId { get; set; }

        /// <summary>
        /// Upload timestamp in UTC - used for audit and GDPR compliance
        /// GDPR: Required for data retention policies
        /// </summary>
        [Required]
        public DateTime UploadedAt { get; set; }

        /// <summary>
        /// User who uploaded the file (from authentication context)
        /// GDPR: Required for accountability and audit trails
        /// </summary>
        [StringLength(100)]
        public string UploadedBy { get; set; }

        /// <summary>
        /// File content type (MIME type) for proper HTTP responses
        /// Examples: application/pdf, image/jpeg, image/png
        /// </summary>
        [Required]
        [StringLength(100)]
        public string ContentType { get; set; }

        /// <summary>
        /// Checksum or hash of file content for integrity verification
        /// GDPR: Used to ensure file integrity and detect tampering
        /// </summary>
        [StringLength(64)]
        public string FileHash { get; set; }

        /// <summary>
        /// Soft delete flag for GDPR right to be forgotten
        /// GDPR: Allows file deletion while maintaining referential integrity
        /// </summary>
        public bool IsDeleted { get; set; } = false;

        /// <summary>
        /// Timestamp when file was marked as deleted
        /// GDPR: Required for data retention and audit purposes
        /// </summary>
        public DateTime? DeletedAt { get; set; }

        /// <summary>
        /// Constructor for Entity Framework - sets default values
        /// </summary>
        public UploadFile()
        {
            UploadedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Constructor for creating new file records with all required data
        /// Ensures GDPR compliance by using secure filenames
        /// </summary>
        public UploadFile(string secureFileName, string originalFileName, string fileType,
                        long fileSize, string fileExtension, string storageUrl,
                        string containerName, string contentType, string uploadedBy)
        {
            SecureFileName = secureFileName;
            OriginalFileName = originalFileName;
            FileType = fileType;
            FileSize = fileSize;
            FileExtension = fileExtension;
            StorageUrl = storageUrl;
            ContainerName = containerName;
            ContentType = contentType;
            UploadedBy = uploadedBy;
            UploadedAt = DateTime.UtcNow;
            IsDeleted = false;
        }

        /// <summary>
        /// Marks file as deleted for GDPR compliance
        /// Actual file deletion from storage happens separately
        /// </summary>
        public void MarkAsDeleted()
        {
            IsDeleted = true;
            DeletedAt = DateTime.UtcNow;
        }

        /// <summary>
        /// Checks if file is an image based on extension
        /// Used for different processing rules for images vs documents
        /// </summary>
        public bool IsImage()
        {
            var imageExtensions = new[] { ".jpg", ".jpeg", ".png", ".gif", ".bmp" };
            return imageExtensions.Contains(FileExtension.ToLower());
        }

        /// <summary>
        /// Checks if file is a contract/document based on extension
        /// Used for different security and processing requirements
        /// </summary>
        public bool IsContract()
        {
            var documentExtensions = new[] { ".pdf", ".doc", ".docx" };
            return documentExtensions.Contains(FileExtension.ToLower());
        }
    }
}
